spring.application.name=JobApp

spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

server.port=8000

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
